### ISSUE TITLE
Mock Data generator

### ISSUE THREAD

**Issue by superalex-dev** [DevDatesDevelopers/Database#1]
Генератор, генериращ тестови (примерни) данни

**Comment by superalex-dev** [comment]
https://github.com/DevDatesDevelopers/Database/commit/aae0c74c074215ca16fcbad4202154fdba236ead

**Comment by superalex-dev** [comment]
@BoyanMilenkov 
Можеш да направиш mock data generator-a със C# ([Bogus](https://zetcode.com/csharp/bogus/)) или Javascript ([Faker.js](https://fakerjs.dev/)). В горния commit съм качил относителен пример как горе долу да използваш faker.js за подобни цели.

**Comment by superalex-dev** [comment]
@BoyanMilenkov 
Качил съм ти почти завършен пример за mock data generator, използвайки Bogus и .Net, прегледай branch-a и моля те започни да работиш!

**Comment by superalex-dev** [comment]
https://github.com/DevDatesDevelopers/Database/commit/64ff55b159493a34e18cc460d75397a3e0b51a15

**Comment by superalex-dev** [comment]
https://github.com/DevDatesDevelopers/DevDatesAPI/commit/679f9aa5f2498e6e2bb361faadbfbe3ca3e6e6fc

**Comment by superalex-dev** [comment]
До къде стигна?

@BoyanMilenkov

**Comment by BoyanMilenkov** [comment]
До никъде извинявай, имах доста работа през ваканцията.

**Comment by superalex-dev** [comment]
> До никъде извинявай, имах доста работа през ваканцията.

Ок не е проблем, тъй като все пак бяхме ваканция, никой не очаква да бачкаш през ваканцията, но е важно в часовете лека по лека да го буташ, за да имаме някакъв прогрес.

**Comment by BoyanMilenkov** [comment]
>
Добре!

**Comment by superalex-dev** [comment]
https://github.com/DevDatesDevelopers/DevDatesAPI/commit/72083f62c321e70f08123702c37fd8d7912d8b41

@Matey-Nikolov @BoyanMilenkov Пишете коментари по задачите тук, за да мога да ви отговарям.

**Comment by Matey-Nikolov** [comment]
[https://github.com/DevDatesDevelopers/DevDatesAPI/commit/3ab73f2b8cb03dcdadb0a4bff44ff88a99bb11aa](url)

Останалата част

**Comment by Matey-Nikolov** [comment]
[https://github.com/DevDatesDevelopers/DevDatesAPI](/commit/3ab73f2b8cb03dcdadb0a4bff44ff88a99bb11aa)

**Comment by Matey-Nikolov** [comment]
https://github.com/DevDatesDevelopers/DevDatesAPI/commit/3ab73f2b8cb03dcdadb0a4bff44ff88a99bb11aa
