### ISSUE TITLE
Public access server (Database)

### ISSUE THREAD

**Issue by superalex-dev** [DevDatesDevelopers/Database#2]
Сървър и база, която да се достъпва от хората, които не са в Database екипа.

**Comment by ktodorov-itarea** [comment]
А точно как да я използваме?

**Comment by superalex-dev** [comment]
> А точно как да я използваме?

public access:
Server name: **devdates.database.windows.net**

login: **public**
Password: **DevDatesPublic123**

**Comment by superalex-dev** [comment]
https://github.com/DevDatesDevelopers/Database/commit/78e618f420be214b5066c94e39be5d071b4debdd

**Comment by superalex-dev** [comment]
https://github.com/DevDatesDevelopers/Database/commit/9baaa9d02c486f1fceec08f4689154b5a2f44c07
