### ISSUE TITLE
SQL DB schema

### ISSUE THREAD

**Issue by superalex-dev** [DevDatesDevelopers/Database#3]

**Comment by ktodorov-itarea** [comment]
Къде е модела на базата?!?

**Comment by superalex-dev** [comment]
> Къде е модела на базата?!?

erDiagram
    Users {
        int Id
        string Name
        DateTime DateOfBirth
        int GenderId
        string Bio
        string Email
        DateTime Created
        DateTime Modified
        string ModifiedBy
    }

    Users ||--|| Genders : choses

   Genders{
        int Id
        string DisplayName
        DateTime Created
        DateTime Modified
        string ModifiedBy
   }

   Users ||--o{ UsersPreferences : choses

   UsersPreferences{
        int UserId
        int GenderId
        DateTime Created
   }

   Resources ||--|| ResourcesTypes : chosen

   ResourcesTypes{
        int Id
        string DisplayName
        DateTime Created
        DateTime Modified
        string ModifiedBy
   }

   Users ||--o{ Resources : choses

   Resources{
        int Id
        int UserId
        string ResourceURI
        int ResourceTypeId
   }

   UsersInterests ||--|| Interests : chosen

   Interests{
        int Id
        string DisplayName
        DateTime Created
        DateTime Modified
        string ModifiedBy
   }

   Users ||--o{ UsersInterests : choses

   UsersInterests{
        int UserId
        int InterestId
   }

   Users ||--o{ Likes : likes

   Likes{

        int LikerId
        int LikedId
        DateTime Created
    }

    Matches{
        int User1Id
        int User2Id
    }

**Comment by superalex-dev** [comment]
https://github.com/DevDatesDevelopers/Database/commit/ada6c24abe150b20a6fc973dc22af5f109bdec97
